# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /media/bigmoth/Eva-02/Fadeout Editor/Fadeout-Fork-UE4-4.24.3
GAMEPROJECTFILE =/media/bigmoth/Eva-02/Fadeout Editor/Grapple/Grapple.uproject

TARGETS = \
	BenchmarkTool-Linux-Debug  \
	BenchmarkTool-Linux-DebugGame  \
	BenchmarkTool-Linux-Shipping  \
	BenchmarkTool-Linux-Test  \
	BenchmarkTool \
	BlankProgram-Linux-Debug  \
	BlankProgram-Linux-DebugGame  \
	BlankProgram-Linux-Shipping  \
	BlankProgram-Linux-Test  \
	BlankProgram \
	BuildPatchTool-Linux-Debug  \
	BuildPatchTool-Linux-DebugGame  \
	BuildPatchTool-Linux-Shipping  \
	BuildPatchTool-Linux-Test  \
	BuildPatchTool \
	CrashReportClient-Linux-Debug  \
	CrashReportClient-Linux-DebugGame  \
	CrashReportClient-Linux-Shipping  \
	CrashReportClient-Linux-Test  \
	CrashReportClient \
	CrashReportClientEditor-Linux-Debug  \
	CrashReportClientEditor-Linux-DebugGame  \
	CrashReportClientEditor-Linux-Shipping  \
	CrashReportClientEditor-Linux-Test  \
	CrashReportClientEditor \
	DatasmithCADWorker-Linux-Debug  \
	DatasmithCADWorker-Linux-DebugGame  \
	DatasmithCADWorker-Linux-Shipping  \
	DatasmithCADWorker-Linux-Test  \
	DatasmithCADWorker \
	DatasmithFacadeCSharp-Linux-Debug  \
	DatasmithFacadeCSharp-Linux-DebugGame  \
	DatasmithFacadeCSharp-Linux-Shipping  \
	DatasmithFacadeCSharp-Linux-Test  \
	DatasmithFacadeCSharp \
	DatasmithMax2016-Linux-Debug  \
	DatasmithMax2016-Linux-DebugGame  \
	DatasmithMax2016-Linux-Shipping  \
	DatasmithMax2016-Linux-Test  \
	DatasmithMax2016 \
	DatasmithMax2017-Linux-Debug  \
	DatasmithMax2017-Linux-DebugGame  \
	DatasmithMax2017-Linux-Shipping  \
	DatasmithMax2017-Linux-Test  \
	DatasmithMax2017 \
	DatasmithMax2018-Linux-Debug  \
	DatasmithMax2018-Linux-DebugGame  \
	DatasmithMax2018-Linux-Shipping  \
	DatasmithMax2018-Linux-Test  \
	DatasmithMax2018 \
	DatasmithMax2019-Linux-Debug  \
	DatasmithMax2019-Linux-DebugGame  \
	DatasmithMax2019-Linux-Shipping  \
	DatasmithMax2019-Linux-Test  \
	DatasmithMax2019 \
	DatasmithMax2020-Linux-Debug  \
	DatasmithMax2020-Linux-DebugGame  \
	DatasmithMax2020-Linux-Shipping  \
	DatasmithMax2020-Linux-Test  \
	DatasmithMax2020 \
	DatasmithRevit2018-Linux-Debug  \
	DatasmithRevit2018-Linux-DebugGame  \
	DatasmithRevit2018-Linux-Shipping  \
	DatasmithRevit2018-Linux-Test  \
	DatasmithRevit2018 \
	DatasmithRevit2019-Linux-Debug  \
	DatasmithRevit2019-Linux-DebugGame  \
	DatasmithRevit2019-Linux-Shipping  \
	DatasmithRevit2019-Linux-Test  \
	DatasmithRevit2019 \
	DatasmithRevit2020-Linux-Debug  \
	DatasmithRevit2020-Linux-DebugGame  \
	DatasmithRevit2020-Linux-Shipping  \
	DatasmithRevit2020-Linux-Test  \
	DatasmithRevit2020 \
	DatasmithSDK-Linux-Debug  \
	DatasmithSDK-Linux-DebugGame  \
	DatasmithSDK-Linux-Shipping  \
	DatasmithSDK-Linux-Test  \
	DatasmithSDK \
	DatasmithSketchUp2017-Linux-Debug  \
	DatasmithSketchUp2017-Linux-DebugGame  \
	DatasmithSketchUp2017-Linux-Shipping  \
	DatasmithSketchUp2017-Linux-Test  \
	DatasmithSketchUp2017 \
	DatasmithSketchUp2018-Linux-Debug  \
	DatasmithSketchUp2018-Linux-DebugGame  \
	DatasmithSketchUp2018-Linux-Shipping  \
	DatasmithSketchUp2018-Linux-Test  \
	DatasmithSketchUp2018 \
	DatasmithSketchUp2019-Linux-Debug  \
	DatasmithSketchUp2019-Linux-DebugGame  \
	DatasmithSketchUp2019-Linux-Shipping  \
	DatasmithSketchUp2019-Linux-Test  \
	DatasmithSketchUp2019 \
	UnrealLaunchDaemon-Linux-Debug  \
	UnrealLaunchDaemon-Linux-DebugGame  \
	UnrealLaunchDaemon-Linux-Shipping  \
	UnrealLaunchDaemon-Linux-Test  \
	UnrealLaunchDaemon \
	LiveCodingConsole-Linux-Debug  \
	LiveCodingConsole-Linux-DebugGame  \
	LiveCodingConsole-Linux-Shipping  \
	LiveCodingConsole-Linux-Test  \
	LiveCodingConsole \
	DsymExporter-Linux-Debug  \
	DsymExporter-Linux-DebugGame  \
	DsymExporter-Linux-Shipping  \
	DsymExporter-Linux-Test  \
	DsymExporter \
	UE4EditorServices-Linux-Debug  \
	UE4EditorServices-Linux-DebugGame  \
	UE4EditorServices-Linux-Shipping  \
	UE4EditorServices-Linux-Test  \
	UE4EditorServices \
	UnrealAtoS-Linux-Debug  \
	UnrealAtoS-Linux-DebugGame  \
	UnrealAtoS-Linux-Shipping  \
	UnrealAtoS-Linux-Test  \
	UnrealAtoS \
	MinidumpDiagnostics-Linux-Debug  \
	MinidumpDiagnostics-Linux-DebugGame  \
	MinidumpDiagnostics-Linux-Shipping  \
	MinidumpDiagnostics-Linux-Test  \
	MinidumpDiagnostics \
	ShaderCompileWorker-Linux-Debug  \
	ShaderCompileWorker-Linux-DebugGame  \
	ShaderCompileWorker-Linux-Shipping  \
	ShaderCompileWorker-Linux-Test  \
	ShaderCompileWorker \
	SlateViewer-Linux-Debug  \
	SlateViewer-Linux-DebugGame  \
	SlateViewer-Linux-Shipping  \
	SlateViewer-Linux-Test  \
	SlateViewer \
	SymbolDebugger-Linux-Debug  \
	SymbolDebugger-Linux-DebugGame  \
	SymbolDebugger-Linux-Shipping  \
	SymbolDebugger-Linux-Test  \
	SymbolDebugger \
	TestPAL-Linux-Debug  \
	TestPAL-Linux-DebugGame  \
	TestPAL-Linux-Shipping  \
	TestPAL-Linux-Test  \
	TestPAL \
	UnrealCEFSubProcess-Linux-Debug  \
	UnrealCEFSubProcess-Linux-DebugGame  \
	UnrealCEFSubProcess-Linux-Shipping  \
	UnrealCEFSubProcess-Linux-Test  \
	UnrealCEFSubProcess \
	UnrealDisasterRecoveryService-Linux-Debug  \
	UnrealDisasterRecoveryService-Linux-DebugGame  \
	UnrealDisasterRecoveryService-Linux-Shipping  \
	UnrealDisasterRecoveryService-Linux-Test  \
	UnrealDisasterRecoveryService \
	UnrealFileServer-Linux-Debug  \
	UnrealFileServer-Linux-DebugGame  \
	UnrealFileServer-Linux-Shipping  \
	UnrealFileServer-Linux-Test  \
	UnrealFileServer \
	UnrealFrontend-Linux-Debug  \
	UnrealFrontend-Linux-DebugGame  \
	UnrealFrontend-Linux-Shipping  \
	UnrealFrontend-Linux-Test  \
	UnrealFrontend \
	UnrealHeaderTool-Linux-Debug  \
	UnrealHeaderTool-Linux-DebugGame  \
	UnrealHeaderTool-Linux-Shipping  \
	UnrealHeaderTool-Linux-Test  \
	UnrealHeaderTool \
	UnrealInsights-Linux-Debug  \
	UnrealInsights-Linux-DebugGame  \
	UnrealInsights-Linux-Shipping  \
	UnrealInsights-Linux-Test  \
	UnrealInsights \
	UnrealInsightsCLI-Linux-Debug  \
	UnrealInsightsCLI-Linux-DebugGame  \
	UnrealInsightsCLI-Linux-Shipping  \
	UnrealInsightsCLI-Linux-Test  \
	UnrealInsightsCLI \
	UnrealLightmass-Linux-Debug  \
	UnrealLightmass-Linux-DebugGame  \
	UnrealLightmass-Linux-Shipping  \
	UnrealLightmass-Linux-Test  \
	UnrealLightmass \
	UnrealMultiUserServer-Linux-Debug  \
	UnrealMultiUserServer-Linux-DebugGame  \
	UnrealMultiUserServer-Linux-Shipping  \
	UnrealMultiUserServer-Linux-Test  \
	UnrealMultiUserServer \
	UnrealPak-Linux-Debug  \
	UnrealPak-Linux-DebugGame  \
	UnrealPak-Linux-Shipping  \
	UnrealPak-Linux-Test  \
	UnrealPak \
	UnrealVersionSelector-Linux-Debug  \
	UnrealVersionSelector-Linux-DebugGame  \
	UnrealVersionSelector-Linux-Shipping  \
	UnrealVersionSelector-Linux-Test  \
	UnrealVersionSelector \
	UnrealWatchdog-Linux-Debug  \
	UnrealWatchdog-Linux-DebugGame  \
	UnrealWatchdog-Linux-Shipping  \
	UnrealWatchdog-Linux-Test  \
	UnrealWatchdog \
	BootstrapPackagedGame-Linux-Debug  \
	BootstrapPackagedGame-Linux-DebugGame  \
	BootstrapPackagedGame-Linux-Shipping  \
	BootstrapPackagedGame-Linux-Test  \
	BootstrapPackagedGame \
	UE4Client-Linux-Debug  \
	UE4Client-Linux-DebugGame  \
	UE4Client-Linux-Shipping  \
	UE4Client-Linux-Test  \
	UE4Client \
	UE4Editor-Linux-Debug  \
	UE4Editor-Linux-DebugGame  \
	UE4Editor-Linux-Shipping  \
	UE4Editor-Linux-Test  \
	UE4Editor \
	UE4Game-Linux-Debug  \
	UE4Game-Linux-DebugGame  \
	UE4Game-Linux-Shipping  \
	UE4Game-Linux-Test  \
	UE4Game \
	UE4Server-Linux-Debug  \
	UE4Server-Linux-DebugGame  \
	UE4Server-Linux-Shipping  \
	UE4Server-Linux-Test  \
	UE4Server \
	Grapple-Linux-Debug  \
	Grapple-Linux-DebugGame  \
	Grapple-Linux-Shipping  \
	Grapple-Linux-Test  \
	Grapple \
	GrappleEditor-Linux-Debug  \
	GrappleEditor-Linux-DebugGame  \
	GrappleEditor-Linux-Shipping  \
	GrappleEditor-Linux-Test  \
	GrappleEditor \
	GrappleServer-Linux-Debug  \
	GrappleServer-Linux-DebugGame  \
	GrappleServer-Linux-Shipping  \
	GrappleServer-Linux-Test  \
	GrappleServer\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/RunMono.sh" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool.exe"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass

StandardSet: RequiredTools UnrealFrontend UE4Editor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug UE4Editor-Linux-Debug


BenchmarkTool-Linux-Debug:
	 $(BUILD) BenchmarkTool Linux Debug  $(ARGS)

BenchmarkTool-Linux-DebugGame:
	 $(BUILD) BenchmarkTool Linux DebugGame  $(ARGS)

BenchmarkTool-Linux-Shipping:
	 $(BUILD) BenchmarkTool Linux Shipping  $(ARGS)

BenchmarkTool-Linux-Test:
	 $(BUILD) BenchmarkTool Linux Test  $(ARGS)

BenchmarkTool:
	 $(BUILD) BenchmarkTool Linux Development  $(ARGS)

BlankProgram-Linux-Debug:
	 $(BUILD) BlankProgram Linux Debug  $(ARGS)

BlankProgram-Linux-DebugGame:
	 $(BUILD) BlankProgram Linux DebugGame  $(ARGS)

BlankProgram-Linux-Shipping:
	 $(BUILD) BlankProgram Linux Shipping  $(ARGS)

BlankProgram-Linux-Test:
	 $(BUILD) BlankProgram Linux Test  $(ARGS)

BlankProgram:
	 $(BUILD) BlankProgram Linux Development  $(ARGS)

BuildPatchTool-Linux-Debug:
	 $(BUILD) BuildPatchTool Linux Debug  $(ARGS)

BuildPatchTool-Linux-DebugGame:
	 $(BUILD) BuildPatchTool Linux DebugGame  $(ARGS)

BuildPatchTool-Linux-Shipping:
	 $(BUILD) BuildPatchTool Linux Shipping  $(ARGS)

BuildPatchTool-Linux-Test:
	 $(BUILD) BuildPatchTool Linux Test  $(ARGS)

BuildPatchTool:
	 $(BUILD) BuildPatchTool Linux Development  $(ARGS)

CrashReportClient-Linux-Debug:
	 $(BUILD) CrashReportClient Linux Debug  $(ARGS)

CrashReportClient-Linux-DebugGame:
	 $(BUILD) CrashReportClient Linux DebugGame  $(ARGS)

CrashReportClient-Linux-Shipping:
	 $(BUILD) CrashReportClient Linux Shipping  $(ARGS)

CrashReportClient-Linux-Test:
	 $(BUILD) CrashReportClient Linux Test  $(ARGS)

CrashReportClient:
	 $(BUILD) CrashReportClient Linux Development  $(ARGS)

CrashReportClientEditor-Linux-Debug:
	 $(BUILD) CrashReportClientEditor Linux Debug  $(ARGS)

CrashReportClientEditor-Linux-DebugGame:
	 $(BUILD) CrashReportClientEditor Linux DebugGame  $(ARGS)

CrashReportClientEditor-Linux-Shipping:
	 $(BUILD) CrashReportClientEditor Linux Shipping  $(ARGS)

CrashReportClientEditor-Linux-Test:
	 $(BUILD) CrashReportClientEditor Linux Test  $(ARGS)

CrashReportClientEditor:
	 $(BUILD) CrashReportClientEditor Linux Development  $(ARGS)

DatasmithCADWorker-Linux-Debug:
	 $(BUILD) DatasmithCADWorker Linux Debug  $(ARGS)

DatasmithCADWorker-Linux-DebugGame:
	 $(BUILD) DatasmithCADWorker Linux DebugGame  $(ARGS)

DatasmithCADWorker-Linux-Shipping:
	 $(BUILD) DatasmithCADWorker Linux Shipping  $(ARGS)

DatasmithCADWorker-Linux-Test:
	 $(BUILD) DatasmithCADWorker Linux Test  $(ARGS)

DatasmithCADWorker:
	 $(BUILD) DatasmithCADWorker Linux Development  $(ARGS)

DatasmithFacadeCSharp-Linux-Debug:
	 $(BUILD) DatasmithFacadeCSharp Linux Debug  $(ARGS)

DatasmithFacadeCSharp-Linux-DebugGame:
	 $(BUILD) DatasmithFacadeCSharp Linux DebugGame  $(ARGS)

DatasmithFacadeCSharp-Linux-Shipping:
	 $(BUILD) DatasmithFacadeCSharp Linux Shipping  $(ARGS)

DatasmithFacadeCSharp-Linux-Test:
	 $(BUILD) DatasmithFacadeCSharp Linux Test  $(ARGS)

DatasmithFacadeCSharp:
	 $(BUILD) DatasmithFacadeCSharp Linux Development  $(ARGS)

DatasmithMax2016-Linux-Debug:
	 $(BUILD) DatasmithMax2016 Linux Debug  $(ARGS)

DatasmithMax2016-Linux-DebugGame:
	 $(BUILD) DatasmithMax2016 Linux DebugGame  $(ARGS)

DatasmithMax2016-Linux-Shipping:
	 $(BUILD) DatasmithMax2016 Linux Shipping  $(ARGS)

DatasmithMax2016-Linux-Test:
	 $(BUILD) DatasmithMax2016 Linux Test  $(ARGS)

DatasmithMax2016:
	 $(BUILD) DatasmithMax2016 Linux Development  $(ARGS)

DatasmithMax2017-Linux-Debug:
	 $(BUILD) DatasmithMax2017 Linux Debug  $(ARGS)

DatasmithMax2017-Linux-DebugGame:
	 $(BUILD) DatasmithMax2017 Linux DebugGame  $(ARGS)

DatasmithMax2017-Linux-Shipping:
	 $(BUILD) DatasmithMax2017 Linux Shipping  $(ARGS)

DatasmithMax2017-Linux-Test:
	 $(BUILD) DatasmithMax2017 Linux Test  $(ARGS)

DatasmithMax2017:
	 $(BUILD) DatasmithMax2017 Linux Development  $(ARGS)

DatasmithMax2018-Linux-Debug:
	 $(BUILD) DatasmithMax2018 Linux Debug  $(ARGS)

DatasmithMax2018-Linux-DebugGame:
	 $(BUILD) DatasmithMax2018 Linux DebugGame  $(ARGS)

DatasmithMax2018-Linux-Shipping:
	 $(BUILD) DatasmithMax2018 Linux Shipping  $(ARGS)

DatasmithMax2018-Linux-Test:
	 $(BUILD) DatasmithMax2018 Linux Test  $(ARGS)

DatasmithMax2018:
	 $(BUILD) DatasmithMax2018 Linux Development  $(ARGS)

DatasmithMax2019-Linux-Debug:
	 $(BUILD) DatasmithMax2019 Linux Debug  $(ARGS)

DatasmithMax2019-Linux-DebugGame:
	 $(BUILD) DatasmithMax2019 Linux DebugGame  $(ARGS)

DatasmithMax2019-Linux-Shipping:
	 $(BUILD) DatasmithMax2019 Linux Shipping  $(ARGS)

DatasmithMax2019-Linux-Test:
	 $(BUILD) DatasmithMax2019 Linux Test  $(ARGS)

DatasmithMax2019:
	 $(BUILD) DatasmithMax2019 Linux Development  $(ARGS)

DatasmithMax2020-Linux-Debug:
	 $(BUILD) DatasmithMax2020 Linux Debug  $(ARGS)

DatasmithMax2020-Linux-DebugGame:
	 $(BUILD) DatasmithMax2020 Linux DebugGame  $(ARGS)

DatasmithMax2020-Linux-Shipping:
	 $(BUILD) DatasmithMax2020 Linux Shipping  $(ARGS)

DatasmithMax2020-Linux-Test:
	 $(BUILD) DatasmithMax2020 Linux Test  $(ARGS)

DatasmithMax2020:
	 $(BUILD) DatasmithMax2020 Linux Development  $(ARGS)

DatasmithRevit2018-Linux-Debug:
	 $(BUILD) DatasmithRevit2018 Linux Debug  $(ARGS)

DatasmithRevit2018-Linux-DebugGame:
	 $(BUILD) DatasmithRevit2018 Linux DebugGame  $(ARGS)

DatasmithRevit2018-Linux-Shipping:
	 $(BUILD) DatasmithRevit2018 Linux Shipping  $(ARGS)

DatasmithRevit2018-Linux-Test:
	 $(BUILD) DatasmithRevit2018 Linux Test  $(ARGS)

DatasmithRevit2018:
	 $(BUILD) DatasmithRevit2018 Linux Development  $(ARGS)

DatasmithRevit2019-Linux-Debug:
	 $(BUILD) DatasmithRevit2019 Linux Debug  $(ARGS)

DatasmithRevit2019-Linux-DebugGame:
	 $(BUILD) DatasmithRevit2019 Linux DebugGame  $(ARGS)

DatasmithRevit2019-Linux-Shipping:
	 $(BUILD) DatasmithRevit2019 Linux Shipping  $(ARGS)

DatasmithRevit2019-Linux-Test:
	 $(BUILD) DatasmithRevit2019 Linux Test  $(ARGS)

DatasmithRevit2019:
	 $(BUILD) DatasmithRevit2019 Linux Development  $(ARGS)

DatasmithRevit2020-Linux-Debug:
	 $(BUILD) DatasmithRevit2020 Linux Debug  $(ARGS)

DatasmithRevit2020-Linux-DebugGame:
	 $(BUILD) DatasmithRevit2020 Linux DebugGame  $(ARGS)

DatasmithRevit2020-Linux-Shipping:
	 $(BUILD) DatasmithRevit2020 Linux Shipping  $(ARGS)

DatasmithRevit2020-Linux-Test:
	 $(BUILD) DatasmithRevit2020 Linux Test  $(ARGS)

DatasmithRevit2020:
	 $(BUILD) DatasmithRevit2020 Linux Development  $(ARGS)

DatasmithSDK-Linux-Debug:
	 $(BUILD) DatasmithSDK Linux Debug  $(ARGS)

DatasmithSDK-Linux-DebugGame:
	 $(BUILD) DatasmithSDK Linux DebugGame  $(ARGS)

DatasmithSDK-Linux-Shipping:
	 $(BUILD) DatasmithSDK Linux Shipping  $(ARGS)

DatasmithSDK-Linux-Test:
	 $(BUILD) DatasmithSDK Linux Test  $(ARGS)

DatasmithSDK:
	 $(BUILD) DatasmithSDK Linux Development  $(ARGS)

DatasmithSketchUp2017-Linux-Debug:
	 $(BUILD) DatasmithSketchUp2017 Linux Debug  $(ARGS)

DatasmithSketchUp2017-Linux-DebugGame:
	 $(BUILD) DatasmithSketchUp2017 Linux DebugGame  $(ARGS)

DatasmithSketchUp2017-Linux-Shipping:
	 $(BUILD) DatasmithSketchUp2017 Linux Shipping  $(ARGS)

DatasmithSketchUp2017-Linux-Test:
	 $(BUILD) DatasmithSketchUp2017 Linux Test  $(ARGS)

DatasmithSketchUp2017:
	 $(BUILD) DatasmithSketchUp2017 Linux Development  $(ARGS)

DatasmithSketchUp2018-Linux-Debug:
	 $(BUILD) DatasmithSketchUp2018 Linux Debug  $(ARGS)

DatasmithSketchUp2018-Linux-DebugGame:
	 $(BUILD) DatasmithSketchUp2018 Linux DebugGame  $(ARGS)

DatasmithSketchUp2018-Linux-Shipping:
	 $(BUILD) DatasmithSketchUp2018 Linux Shipping  $(ARGS)

DatasmithSketchUp2018-Linux-Test:
	 $(BUILD) DatasmithSketchUp2018 Linux Test  $(ARGS)

DatasmithSketchUp2018:
	 $(BUILD) DatasmithSketchUp2018 Linux Development  $(ARGS)

DatasmithSketchUp2019-Linux-Debug:
	 $(BUILD) DatasmithSketchUp2019 Linux Debug  $(ARGS)

DatasmithSketchUp2019-Linux-DebugGame:
	 $(BUILD) DatasmithSketchUp2019 Linux DebugGame  $(ARGS)

DatasmithSketchUp2019-Linux-Shipping:
	 $(BUILD) DatasmithSketchUp2019 Linux Shipping  $(ARGS)

DatasmithSketchUp2019-Linux-Test:
	 $(BUILD) DatasmithSketchUp2019 Linux Test  $(ARGS)

DatasmithSketchUp2019:
	 $(BUILD) DatasmithSketchUp2019 Linux Development  $(ARGS)

UnrealLaunchDaemon-Linux-Debug:
	 $(BUILD) UnrealLaunchDaemon Linux Debug  $(ARGS)

UnrealLaunchDaemon-Linux-DebugGame:
	 $(BUILD) UnrealLaunchDaemon Linux DebugGame  $(ARGS)

UnrealLaunchDaemon-Linux-Shipping:
	 $(BUILD) UnrealLaunchDaemon Linux Shipping  $(ARGS)

UnrealLaunchDaemon-Linux-Test:
	 $(BUILD) UnrealLaunchDaemon Linux Test  $(ARGS)

UnrealLaunchDaemon:
	 $(BUILD) UnrealLaunchDaemon Linux Development  $(ARGS)

LiveCodingConsole-Linux-Debug:
	 $(BUILD) LiveCodingConsole Linux Debug  $(ARGS)

LiveCodingConsole-Linux-DebugGame:
	 $(BUILD) LiveCodingConsole Linux DebugGame  $(ARGS)

LiveCodingConsole-Linux-Shipping:
	 $(BUILD) LiveCodingConsole Linux Shipping  $(ARGS)

LiveCodingConsole-Linux-Test:
	 $(BUILD) LiveCodingConsole Linux Test  $(ARGS)

LiveCodingConsole:
	 $(BUILD) LiveCodingConsole Linux Development  $(ARGS)

DsymExporter-Linux-Debug:
	 $(BUILD) DsymExporter Linux Debug  $(ARGS)

DsymExporter-Linux-DebugGame:
	 $(BUILD) DsymExporter Linux DebugGame  $(ARGS)

DsymExporter-Linux-Shipping:
	 $(BUILD) DsymExporter Linux Shipping  $(ARGS)

DsymExporter-Linux-Test:
	 $(BUILD) DsymExporter Linux Test  $(ARGS)

DsymExporter:
	 $(BUILD) DsymExporter Linux Development  $(ARGS)

UE4EditorServices-Linux-Debug:
	 $(BUILD) UE4EditorServices Linux Debug  $(ARGS)

UE4EditorServices-Linux-DebugGame:
	 $(BUILD) UE4EditorServices Linux DebugGame  $(ARGS)

UE4EditorServices-Linux-Shipping:
	 $(BUILD) UE4EditorServices Linux Shipping  $(ARGS)

UE4EditorServices-Linux-Test:
	 $(BUILD) UE4EditorServices Linux Test  $(ARGS)

UE4EditorServices:
	 $(BUILD) UE4EditorServices Linux Development  $(ARGS)

UnrealAtoS-Linux-Debug:
	 $(BUILD) UnrealAtoS Linux Debug  $(ARGS)

UnrealAtoS-Linux-DebugGame:
	 $(BUILD) UnrealAtoS Linux DebugGame  $(ARGS)

UnrealAtoS-Linux-Shipping:
	 $(BUILD) UnrealAtoS Linux Shipping  $(ARGS)

UnrealAtoS-Linux-Test:
	 $(BUILD) UnrealAtoS Linux Test  $(ARGS)

UnrealAtoS:
	 $(BUILD) UnrealAtoS Linux Development  $(ARGS)

MinidumpDiagnostics-Linux-Debug:
	 $(BUILD) MinidumpDiagnostics Linux Debug  $(ARGS)

MinidumpDiagnostics-Linux-DebugGame:
	 $(BUILD) MinidumpDiagnostics Linux DebugGame  $(ARGS)

MinidumpDiagnostics-Linux-Shipping:
	 $(BUILD) MinidumpDiagnostics Linux Shipping  $(ARGS)

MinidumpDiagnostics-Linux-Test:
	 $(BUILD) MinidumpDiagnostics Linux Test  $(ARGS)

MinidumpDiagnostics:
	 $(BUILD) MinidumpDiagnostics Linux Development  $(ARGS)

ShaderCompileWorker-Linux-Debug:
	 $(BUILD) ShaderCompileWorker Linux Debug  $(ARGS)

ShaderCompileWorker-Linux-DebugGame:
	 $(BUILD) ShaderCompileWorker Linux DebugGame  $(ARGS)

ShaderCompileWorker-Linux-Shipping:
	 $(BUILD) ShaderCompileWorker Linux Shipping  $(ARGS)

ShaderCompileWorker-Linux-Test:
	 $(BUILD) ShaderCompileWorker Linux Test  $(ARGS)

ShaderCompileWorker:
	 $(BUILD) ShaderCompileWorker Linux Development  $(ARGS)

SlateViewer-Linux-Debug:
	 $(BUILD) SlateViewer Linux Debug  $(ARGS)

SlateViewer-Linux-DebugGame:
	 $(BUILD) SlateViewer Linux DebugGame  $(ARGS)

SlateViewer-Linux-Shipping:
	 $(BUILD) SlateViewer Linux Shipping  $(ARGS)

SlateViewer-Linux-Test:
	 $(BUILD) SlateViewer Linux Test  $(ARGS)

SlateViewer:
	 $(BUILD) SlateViewer Linux Development  $(ARGS)

SymbolDebugger-Linux-Debug:
	 $(BUILD) SymbolDebugger Linux Debug  $(ARGS)

SymbolDebugger-Linux-DebugGame:
	 $(BUILD) SymbolDebugger Linux DebugGame  $(ARGS)

SymbolDebugger-Linux-Shipping:
	 $(BUILD) SymbolDebugger Linux Shipping  $(ARGS)

SymbolDebugger-Linux-Test:
	 $(BUILD) SymbolDebugger Linux Test  $(ARGS)

SymbolDebugger:
	 $(BUILD) SymbolDebugger Linux Development  $(ARGS)

TestPAL-Linux-Debug:
	 $(BUILD) TestPAL Linux Debug  $(ARGS)

TestPAL-Linux-DebugGame:
	 $(BUILD) TestPAL Linux DebugGame  $(ARGS)

TestPAL-Linux-Shipping:
	 $(BUILD) TestPAL Linux Shipping  $(ARGS)

TestPAL-Linux-Test:
	 $(BUILD) TestPAL Linux Test  $(ARGS)

TestPAL:
	 $(BUILD) TestPAL Linux Development  $(ARGS)

UnrealCEFSubProcess-Linux-Debug:
	 $(BUILD) UnrealCEFSubProcess Linux Debug  $(ARGS)

UnrealCEFSubProcess-Linux-DebugGame:
	 $(BUILD) UnrealCEFSubProcess Linux DebugGame  $(ARGS)

UnrealCEFSubProcess-Linux-Shipping:
	 $(BUILD) UnrealCEFSubProcess Linux Shipping  $(ARGS)

UnrealCEFSubProcess-Linux-Test:
	 $(BUILD) UnrealCEFSubProcess Linux Test  $(ARGS)

UnrealCEFSubProcess:
	 $(BUILD) UnrealCEFSubProcess Linux Development  $(ARGS)

UnrealDisasterRecoveryService-Linux-Debug:
	 $(BUILD) UnrealDisasterRecoveryService Linux Debug  $(ARGS)

UnrealDisasterRecoveryService-Linux-DebugGame:
	 $(BUILD) UnrealDisasterRecoveryService Linux DebugGame  $(ARGS)

UnrealDisasterRecoveryService-Linux-Shipping:
	 $(BUILD) UnrealDisasterRecoveryService Linux Shipping  $(ARGS)

UnrealDisasterRecoveryService-Linux-Test:
	 $(BUILD) UnrealDisasterRecoveryService Linux Test  $(ARGS)

UnrealDisasterRecoveryService:
	 $(BUILD) UnrealDisasterRecoveryService Linux Development  $(ARGS)

UnrealFileServer-Linux-Debug:
	 $(BUILD) UnrealFileServer Linux Debug  $(ARGS)

UnrealFileServer-Linux-DebugGame:
	 $(BUILD) UnrealFileServer Linux DebugGame  $(ARGS)

UnrealFileServer-Linux-Shipping:
	 $(BUILD) UnrealFileServer Linux Shipping  $(ARGS)

UnrealFileServer-Linux-Test:
	 $(BUILD) UnrealFileServer Linux Test  $(ARGS)

UnrealFileServer:
	 $(BUILD) UnrealFileServer Linux Development  $(ARGS)

UnrealFrontend-Linux-Debug:
	 $(BUILD) UnrealFrontend Linux Debug  $(ARGS)

UnrealFrontend-Linux-DebugGame:
	 $(BUILD) UnrealFrontend Linux DebugGame  $(ARGS)

UnrealFrontend-Linux-Shipping:
	 $(BUILD) UnrealFrontend Linux Shipping  $(ARGS)

UnrealFrontend-Linux-Test:
	 $(BUILD) UnrealFrontend Linux Test  $(ARGS)

UnrealFrontend:
	 $(BUILD) UnrealFrontend Linux Development  $(ARGS)

UnrealHeaderTool-Linux-Debug:
	 $(BUILD) UnrealHeaderTool Linux Debug  $(ARGS)

UnrealHeaderTool-Linux-DebugGame:
	 $(BUILD) UnrealHeaderTool Linux DebugGame  $(ARGS)

UnrealHeaderTool-Linux-Shipping:
	 $(BUILD) UnrealHeaderTool Linux Shipping  $(ARGS)

UnrealHeaderTool-Linux-Test:
	 $(BUILD) UnrealHeaderTool Linux Test  $(ARGS)

UnrealHeaderTool:
	 $(BUILD) UnrealHeaderTool Linux Development  $(ARGS)

UnrealInsights-Linux-Debug:
	 $(BUILD) UnrealInsights Linux Debug  $(ARGS)

UnrealInsights-Linux-DebugGame:
	 $(BUILD) UnrealInsights Linux DebugGame  $(ARGS)

UnrealInsights-Linux-Shipping:
	 $(BUILD) UnrealInsights Linux Shipping  $(ARGS)

UnrealInsights-Linux-Test:
	 $(BUILD) UnrealInsights Linux Test  $(ARGS)

UnrealInsights:
	 $(BUILD) UnrealInsights Linux Development  $(ARGS)

UnrealInsightsCLI-Linux-Debug:
	 $(BUILD) UnrealInsightsCLI Linux Debug  $(ARGS)

UnrealInsightsCLI-Linux-DebugGame:
	 $(BUILD) UnrealInsightsCLI Linux DebugGame  $(ARGS)

UnrealInsightsCLI-Linux-Shipping:
	 $(BUILD) UnrealInsightsCLI Linux Shipping  $(ARGS)

UnrealInsightsCLI-Linux-Test:
	 $(BUILD) UnrealInsightsCLI Linux Test  $(ARGS)

UnrealInsightsCLI:
	 $(BUILD) UnrealInsightsCLI Linux Development  $(ARGS)

UnrealLightmass-Linux-Debug:
	 $(BUILD) UnrealLightmass Linux Debug  $(ARGS)

UnrealLightmass-Linux-DebugGame:
	 $(BUILD) UnrealLightmass Linux DebugGame  $(ARGS)

UnrealLightmass-Linux-Shipping:
	 $(BUILD) UnrealLightmass Linux Shipping  $(ARGS)

UnrealLightmass-Linux-Test:
	 $(BUILD) UnrealLightmass Linux Test  $(ARGS)

UnrealLightmass:
	 $(BUILD) UnrealLightmass Linux Development  $(ARGS)

UnrealMultiUserServer-Linux-Debug:
	 $(BUILD) UnrealMultiUserServer Linux Debug  $(ARGS)

UnrealMultiUserServer-Linux-DebugGame:
	 $(BUILD) UnrealMultiUserServer Linux DebugGame  $(ARGS)

UnrealMultiUserServer-Linux-Shipping:
	 $(BUILD) UnrealMultiUserServer Linux Shipping  $(ARGS)

UnrealMultiUserServer-Linux-Test:
	 $(BUILD) UnrealMultiUserServer Linux Test  $(ARGS)

UnrealMultiUserServer:
	 $(BUILD) UnrealMultiUserServer Linux Development  $(ARGS)

UnrealPak-Linux-Debug:
	 $(BUILD) UnrealPak Linux Debug  $(ARGS)

UnrealPak-Linux-DebugGame:
	 $(BUILD) UnrealPak Linux DebugGame  $(ARGS)

UnrealPak-Linux-Shipping:
	 $(BUILD) UnrealPak Linux Shipping  $(ARGS)

UnrealPak-Linux-Test:
	 $(BUILD) UnrealPak Linux Test  $(ARGS)

UnrealPak:
	 $(BUILD) UnrealPak Linux Development  $(ARGS)

UnrealVersionSelector-Linux-Debug:
	 $(BUILD) UnrealVersionSelector Linux Debug  $(ARGS)

UnrealVersionSelector-Linux-DebugGame:
	 $(BUILD) UnrealVersionSelector Linux DebugGame  $(ARGS)

UnrealVersionSelector-Linux-Shipping:
	 $(BUILD) UnrealVersionSelector Linux Shipping  $(ARGS)

UnrealVersionSelector-Linux-Test:
	 $(BUILD) UnrealVersionSelector Linux Test  $(ARGS)

UnrealVersionSelector:
	 $(BUILD) UnrealVersionSelector Linux Development  $(ARGS)

UnrealWatchdog-Linux-Debug:
	 $(BUILD) UnrealWatchdog Linux Debug  $(ARGS)

UnrealWatchdog-Linux-DebugGame:
	 $(BUILD) UnrealWatchdog Linux DebugGame  $(ARGS)

UnrealWatchdog-Linux-Shipping:
	 $(BUILD) UnrealWatchdog Linux Shipping  $(ARGS)

UnrealWatchdog-Linux-Test:
	 $(BUILD) UnrealWatchdog Linux Test  $(ARGS)

UnrealWatchdog:
	 $(BUILD) UnrealWatchdog Linux Development  $(ARGS)

BootstrapPackagedGame-Linux-Debug:
	 $(BUILD) BootstrapPackagedGame Linux Debug  $(ARGS)

BootstrapPackagedGame-Linux-DebugGame:
	 $(BUILD) BootstrapPackagedGame Linux DebugGame  $(ARGS)

BootstrapPackagedGame-Linux-Shipping:
	 $(BUILD) BootstrapPackagedGame Linux Shipping  $(ARGS)

BootstrapPackagedGame-Linux-Test:
	 $(BUILD) BootstrapPackagedGame Linux Test  $(ARGS)

BootstrapPackagedGame:
	 $(BUILD) BootstrapPackagedGame Linux Development  $(ARGS)

UE4Client-Linux-Debug:
	 $(BUILD) UE4Client Linux Debug  $(ARGS)

UE4Client-Linux-DebugGame:
	 $(BUILD) UE4Client Linux DebugGame  $(ARGS)

UE4Client-Linux-Shipping:
	 $(BUILD) UE4Client Linux Shipping  $(ARGS)

UE4Client-Linux-Test:
	 $(BUILD) UE4Client Linux Test  $(ARGS)

UE4Client:
	 $(BUILD) UE4Client Linux Development  $(ARGS)

UE4Editor-Linux-Debug:
	 $(BUILD) UE4Editor Linux Debug  $(ARGS)

UE4Editor-Linux-DebugGame:
	 $(BUILD) UE4Editor Linux DebugGame  $(ARGS)

UE4Editor-Linux-Shipping:
	 $(BUILD) UE4Editor Linux Shipping  $(ARGS)

UE4Editor-Linux-Test:
	 $(BUILD) UE4Editor Linux Test  $(ARGS)

UE4Editor:
	 $(BUILD) UE4Editor Linux Development  $(ARGS)

UE4Game-Linux-Debug:
	 $(BUILD) UE4Game Linux Debug  $(ARGS)

UE4Game-Linux-DebugGame:
	 $(BUILD) UE4Game Linux DebugGame  $(ARGS)

UE4Game-Linux-Shipping:
	 $(BUILD) UE4Game Linux Shipping  $(ARGS)

UE4Game-Linux-Test:
	 $(BUILD) UE4Game Linux Test  $(ARGS)

UE4Game:
	 $(BUILD) UE4Game Linux Development  $(ARGS)

UE4Server-Linux-Debug:
	 $(BUILD) UE4Server Linux Debug  $(ARGS)

UE4Server-Linux-DebugGame:
	 $(BUILD) UE4Server Linux DebugGame  $(ARGS)

UE4Server-Linux-Shipping:
	 $(BUILD) UE4Server Linux Shipping  $(ARGS)

UE4Server-Linux-Test:
	 $(BUILD) UE4Server Linux Test  $(ARGS)

UE4Server:
	 $(BUILD) UE4Server Linux Development  $(ARGS)

Grapple-Linux-Debug:
	 $(PROJECTBUILD) Grapple Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

Grapple-Linux-DebugGame:
	 $(PROJECTBUILD) Grapple Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

Grapple-Linux-Shipping:
	 $(PROJECTBUILD) Grapple Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

Grapple-Linux-Test:
	 $(PROJECTBUILD) Grapple Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

Grapple:
	 $(PROJECTBUILD) Grapple Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

GrappleEditor-Linux-Debug:
	 $(PROJECTBUILD) GrappleEditor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

GrappleEditor-Linux-DebugGame:
	 $(PROJECTBUILD) GrappleEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

GrappleEditor-Linux-Shipping:
	 $(PROJECTBUILD) GrappleEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

GrappleEditor-Linux-Test:
	 $(PROJECTBUILD) GrappleEditor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

GrappleEditor:
	 $(PROJECTBUILD) GrappleEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

GrappleServer-Linux-Debug:
	 $(BUILD) GrappleServer Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

GrappleServer-Linux-DebugGame:
	 $(BUILD) GrappleServer Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

GrappleServer-Linux-Shipping:
	 $(BUILD) GrappleServer Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

GrappleServer-Linux-Test:
	 $(BUILD) GrappleServer Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

GrappleServer:
	 $(BUILD) GrappleServer Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
